### ISSUE TITLE
e-ink-display-v020 or e-ink-display-v020－teardrop is the latest

### ISSUE THREAD

**Issue by martonmiklos** [kennethlimcp/oshw-design#2]
Hi @kennethlimcp 

Many thanks for sharing your designs!

I am planning to build some electronics to drive an LB060S01 E-ink display, and your design seems to be a good starting point (it's drawn in EAGLE, uses STM32 etc.)

Which one is the latest of the mentioned two designs? Are there any difference between them other than the VIA teardrops? Are there any known issues with them (if you built these versions)?

Thanks in advance!

**Comment by kennethlimcp** [comment]
sorry for the late response

Teardrop is like a manufacturing enhancement to `teardrop` the pads for better reliability.

You can use the non-teardrop copy for edits.

I have to say that the design was not fully working and will be awesome if you managed to test and get it running!

**Comment by martonmiklos** [comment]
Hi @kennethlimcp 

> I have to say that the design was not fully working and will be awesome if you managed to test and get it running!

Can you say a few words about your issues? I started to redesign it a bit (adding tag connect and a few other pokes what I need), so any experience about the board would be useful before I send it to manufacturing.
